version: '3'
services:
  app:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"  # Chainlit
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=sqlite:///app.db
  db:
    image: nouchka/sqlite3
    volumes:
      - ./data/db:/root/db